# Generated by Django 4.2.6 on 2023-10-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_staff_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notifications',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
