# Generated by Django 4.2.5 on 2023-09-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='staff_table',
        ),
    ]
