# Generated by Django 4.2.4 on 2023-09-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('CS&IT', 'CS&IT'), ('AI&DS', 'AI&DS'), ('ECS', 'ECE'), ('EEE', 'EEE'), ('IoT', 'IoT'), ('BT', 'BT'), ('ME', 'ME'), ('CIVIL', 'CIVIL')], max_length=50)),
                ('program', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech')], max_length=30)),
                ('academic_year', models.CharField(choices=[('2020-2021', '2020-21'), ('2021-2022', '2021-22'), ('2022-2023', '2022-23'), ('2023-2024', '2023-24')], max_length=100)),
                ('semester', models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN'), ('SUMMER', 'SUMMER')], max_length=10)),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=10)),
            ],
            options={
                'db_table': 'course_table',
            },
        ),
        migrations.CreateModel(
            name='Session_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.CharField(max_length=100)),
                ('session_end', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'session_year_table',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'STAFF'), (3, 'STUDENT')], default=1, max_length=50),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user_table',
        ),
    ]
