# Generated by Django 4.2.6 on 2023-10-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_data_staff_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_leave',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
